### ISSUE TITLE
After running the setup, my antivirus app keeps blocking some kind of website

### ISSUE THREAD

**Issue by Onyx3349** [hugopilot/fl-studio-discord-rpc#11] opened 2023-08-28 17:44 UTC
I downloaded the rich presence setup for my fl studio 21, and my antivirus app now blocks some kind of api.packetshare.io website.
Should I be worried? How can i uninstall the rich presence thing?

**Comment by MissWomanLiker** [comment] 2023-12-27 14:58
Not exactly an expert but you only really see unsolicited connections to packetshare in malware. packetshare doesn't show up in the repo, so it might be being pulled from elsewhere. Good response from dev btw, absolute radio silence

**Comment by showengineer** [comment] 2023-12-27 15:16
It's weird that there are api calls to packetshare.io, they might be done through the RPC library, which I do not own. You can check the source, it doesn't do any calls to that site (or any for that matter).

**Comment by showengineer** [comment] 2023-12-27 15:56
>  Good response from dev btw, absolute radio silence

@MissWomanLiker As you may have noticed on my profile activity and the last commit date, I am not actively maintaining this project anymore. I simply do not have the time to respond to all issues anymore.
Even though the installer installs a pre-compiled binary, the source build is be reproducible and you can easily check if the source build is the same as the pre-compiled binary. Heck, you can even decompile the entire thing back to it's original source code because IIRC the installer also extracts  a symbol file for the binary.

So instead of suggesting I am distributing malware without any research or proof, forking the project  appending `without-malware-kek` to its name and leaving a salty comment, do research and if there is any malware report the repo or contact the dev directly.

**Comment by showengineer** [comment] 2023-12-27 16:03
Uninstalling can be simply done by deleting the folder from your program files. 

Since the API calls your AV is whining about (which is likely a false positive anyways) do not come directly from my code I am closing this issue.

**Closed as not planned** 2023-12-27 16:03 UTC
